import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import axios from 'axios';

export default function Home() {
  const [query, setQuery] = useState('');
  const [result, setResult] = useState([]);
  let firstQuery = true;

  const handlePesquisa = () => {
    firstQuery = false;
    axios({
      url: `http://localhost:8000/artista/${query}`,
      method: 'GET',
    }).then(artists => {
      if (artists) {
        console.log(artists);
        setResult(artists.data);
      }
    }).catch(error => {
      console.log(error);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Artists Recomendation APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo amante da música!
        </h1>

        <p className={styles.description}>
          Começe digitando o nome do artista que deseja buscar:
        </p>

        <div className={styles.form}>
          <form>
            <div>
              <label>
                <input type="text" value={query} onChange={e => setQuery(e.target.value)} />
              </label>
            </div>
          </form>
          <button onClick={handlePesquisa}>Pesquisar</button>
        </div>
        <div className={styles.result}>
          {result.length > 0 ?
            <div className={styles.lista}>
              {result.map(artista => (
                <div key={artista.id}>
                  <Link href={`/recomendation?idartista=${artista.id}`}>
                    <a className={styles.card}>
                      <div className={styles.imagem}>
                        {artista.images.length > 0 ? <Image
                          src={`` + artista.images[0].url}
                          alt="Picture of the artist"
                          width={100}
                          height={100}
                          blurDataURL="data:..."
                          placeholder="blur"
                        /> :
                          <Image
                            src={`https://thumbs.dreamstime.com/b/musician-icon-189244196.jpg`}
                            alt="Picture of the artist"
                            width={100}
                            height={100}
                            blurDataURL="data:..."
                            placeholder="blur"
                          />
                        }
                      </div>
                      <div className={styles.info}>
                        <div><b>Nome: </b> {artista.name}</div>
                        <div><b>Gêneros: </b> {artista.genres.map(genero => (
                          <p key={genero}>{genero + ", "} </p>
                        ))}</div>
                      </div>
                    </a>
                  </Link>
                </div>
              ))}
            </div>
            : firstQuery ? <div className="Aviso"><h3>Busque algum artista para ver resultados.</h3></div>
              : <div className="Aviso"><h3>Nenhum resultado para esta busca.</h3></div>
          }
        </div>
      </main>
    </div>
  )
}
